#!/bin/sh

# /x/y/pico-sdl /a/b/c/d.c

PICO=$(dirname $(realpath "$0"))    # /x/y/

VALGRIND="valgrind --leak-check=full --show-leak-kinds=all \
            --errors-for-leak-kinds=all \
            --track-origins=yes --suppressions=$PICO/valgrind.supp \
            --error-exitcode=1"

DIR=$(dirname -- "$1")              # /a/b/c/
EXE=$(basename -- "$1")             # d.c
EXE="${EXE%.*}.exe"                 # d.exe

# PICO_CHECK_INT defaults to enabled, set to empty to disable
# PICO_CHECK_ASR defaults to disabled, set to any value to enable
DEFINES=""
if [ "${PICO_CHECK_INT-1}" != "" ]; then
    DEFINES="$DEFINES -DPICO_CHECK_INT"
fi
if [ -n "$PICO_CHECK_ASR" ]; then
    DEFINES="$DEFINES -DPICO_CHECK_ASR"
fi
if [ -n "$PICO_TESTS" ]; then
    DEFINES="$DEFINES -DPICO_TESTS"
fi

#echo $PICO, $DIR, $EXE

gcc -Wall -g -o "$DIR/$EXE" "$1" \
    "$PICO/src/pico.c"           \
    -I "$PICO/src"               \
    $DEFINES                     \
    -lSDL2 -lSDL2_ttf -lSDL2_image -lSDL2_mixer -lSDL2_gfx \
        || exit 1

cd $DIR/
if [ -n "$PICO_TESTS" ]; then
    $VALGRIND "./$EXE"
else
    "./$EXE"
fi
