#!/bin/sh

PICO=$(dirname -- "$0")

DIR=$(dirname -- "$1")
EXE=$(basename -- "$1")
EXE="${EXE%.*}"

gcc -Wall -o "$DIR/$EXE" "$1" "$PICO/src/pico.c" "$PICO/src/dir.c" "$PICO/src/hash.c" -lSDL2 -lSDL2_ttf -lSDL2_image -lSDL2_mixer -lSDL2_gfx

"$DIR/$EXE"
