#!/bin/sh

VERSION=dev-apr-16

if [ "$1" = --help ]; then
    echo "Usage: pico-lua [options] [file.lua]"
    echo ""
    echo "Options:"
    echo "  --help       Show this help"
    echo "  --version    Show version"
    echo ""
    echo "Without arguments, starts interactive mode."
    exit 0
elif [ "$1" = --version ]; then
    echo pico-lua $VERSION
    exit 0
fi

PICO=$(dirname $(realpath "$0"))/../   # pico-sdl root

LUA=lua5.4
DIR=$(dirname -- "$1")  # /a/b/c
EXE=$(basename -- "$1") # x.lua

VALGRIND="valgrind -q --leak-check=no --track-origins=yes \
            --suppressions=$PICO/valgrind.supp --error-exitcode=1"

cd $DIR/
if [ -n "$PICO_TESTS" ]; then
    $VALGRIND $LUA -lpico $EXE
else
    $LUA -lpico $EXE
fi
