#ifndef PICO_ANCHORS_H
#define PICO_ANCHORS_H

#define PICO_ANCHOR_LEFT   0
#define PICO_ANCHOR_CENTER 0.5
#define PICO_ANCHOR_RIGHT  1
#define PICO_ANCHOR_TOP    0
#define PICO_ANCHOR_MIDDLE 0.5
#define PICO_ANCHOR_BOTTOM 1

extern const Pico_Pct_XY PICO_ANCHOR_C;
extern const Pico_Pct_XY PICO_ANCHOR_NW;
extern const Pico_Pct_XY PICO_ANCHOR_N;
extern const Pico_Pct_XY PICO_ANCHOR_NE;
extern const Pico_Pct_XY PICO_ANCHOR_E;
extern const Pico_Pct_XY PICO_ANCHOR_SE;
extern const Pico_Pct_XY PICO_ANCHOR_S;
extern const Pico_Pct_XY PICO_ANCHOR_SW;
extern const Pico_Pct_XY PICO_ANCHOR_W;

#endif // PICO_ANCHORS_H

#ifdef PICO_ANCHORS_C

const Pico_Pct_XY PICO_ANCHOR_C  = { PICO_ANCHOR_CENTER, PICO_ANCHOR_MIDDLE };
const Pico_Pct_XY PICO_ANCHOR_NW = { PICO_ANCHOR_LEFT,   PICO_ANCHOR_TOP    };
const Pico_Pct_XY PICO_ANCHOR_N  = { PICO_ANCHOR_CENTER, PICO_ANCHOR_TOP    };
const Pico_Pct_XY PICO_ANCHOR_NE = { PICO_ANCHOR_RIGHT,  PICO_ANCHOR_TOP    };
const Pico_Pct_XY PICO_ANCHOR_E  = { PICO_ANCHOR_RIGHT,  PICO_ANCHOR_MIDDLE };
const Pico_Pct_XY PICO_ANCHOR_SE = { PICO_ANCHOR_RIGHT,  PICO_ANCHOR_BOTTOM };
const Pico_Pct_XY PICO_ANCHOR_S  = { PICO_ANCHOR_CENTER, PICO_ANCHOR_BOTTOM };
const Pico_Pct_XY PICO_ANCHOR_SW = { PICO_ANCHOR_LEFT,   PICO_ANCHOR_BOTTOM };
const Pico_Pct_XY PICO_ANCHOR_W  = { PICO_ANCHOR_LEFT,   PICO_ANCHOR_MIDDLE };

#endif // PICO_ANCHORS_C
